/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as FractionalGoldRouteImport } from './routes/fractional-gold'
import { Route as GiftingRouteImport } from './routes/gifting'
import { Route as GiftingNewRouteImport } from './routes/gifting-new'
import { Route as HomeOldVerRouteImport } from './routes/home-old-ver'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as PreciousMetalRouteImport } from './routes/precious-metal'
import { Route as VaultRouteImport } from './routes/vault'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const FractionalGoldRoute = FractionalGoldRouteImport.update({
  id: '/fractional-gold',
  path: '/fractional-gold',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftingRoute = GiftingRouteImport.update({
  id: '/gifting',
  path: '/gifting',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftingNewRoute = GiftingNewRouteImport.update({
  id: '/gifting-new',
  path: '/gifting-new',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeOldVerRoute = HomeOldVerRouteImport.update({
  id: '/home-old-ver',
  path: '/home-old-ver',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const PreciousMetalRoute = PreciousMetalRouteImport.update({
  id: '/precious-metal',
  path: '/precious-metal',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/fractional-gold': typeof FractionalGoldRoute
  '/gifting': typeof GiftingRoute
  '/gifting-new': typeof GiftingNewRoute
  '/home-old-ver': typeof HomeOldVerRoute
  '/learn': typeof LearnRoute
  '/precious-metal': typeof PreciousMetalRoute
  '/vault': typeof VaultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/fractional-gold': typeof FractionalGoldRoute
  '/gifting': typeof GiftingRoute
  '/gifting-new': typeof GiftingNewRoute
  '/home-old-ver': typeof HomeOldVerRoute
  '/learn': typeof LearnRoute
  '/precious-metal': typeof PreciousMetalRoute
  '/vault': typeof VaultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/fractional-gold': typeof FractionalGoldRoute
  '/gifting': typeof GiftingRoute
  '/gifting-new': typeof GiftingNewRoute
  '/home-old-ver': typeof HomeOldVerRoute
  '/learn': typeof LearnRoute
  '/precious-metal': typeof PreciousMetalRoute
  '/vault': typeof VaultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/fractional-gold'
    | '/gifting'
    | '/gifting-new'
    | '/home-old-ver'
    | '/learn'
    | '/precious-metal'
    | '/vault'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/fractional-gold'
    | '/gifting'
    | '/gifting-new'
    | '/home-old-ver'
    | '/learn'
    | '/precious-metal'
    | '/vault'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/fractional-gold'
    | '/gifting'
    | '/gifting-new'
    | '/home-old-ver'
    | '/learn'
    | '/precious-metal'
    | '/vault'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  FractionalGoldRoute: typeof FractionalGoldRoute
  GiftingRoute: typeof GiftingRoute
  GiftingNewRoute: typeof GiftingNewRoute
  HomeOldVerRoute: typeof HomeOldVerRoute
  LearnRoute: typeof LearnRoute
  PreciousMetalRoute: typeof PreciousMetalRoute
  VaultRoute: typeof VaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fractional-gold': {
      id: '/fractional-gold'
      path: '/fractional-gold'
      fullPath: '/fractional-gold'
      preLoaderRoute: typeof FractionalGoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifting': {
      id: '/gifting'
      path: '/gifting'
      fullPath: '/gifting'
      preLoaderRoute: typeof GiftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifting-new': {
      id: '/gifting-new'
      path: '/gifting-new'
      fullPath: '/gifting-new'
      preLoaderRoute: typeof GiftingNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-old-ver': {
      id: '/home-old-ver'
      path: '/home-old-ver'
      fullPath: '/home-old-ver'
      preLoaderRoute: typeof HomeOldVerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precious-metal': {
      id: '/precious-metal'
      path: '/precious-metal'
      fullPath: '/precious-metal'
      preLoaderRoute: typeof PreciousMetalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  FractionalGoldRoute: FractionalGoldRoute,
  GiftingRoute: GiftingRoute,
  GiftingNewRoute: GiftingNewRoute,
  HomeOldVerRoute: HomeOldVerRoute,
  LearnRoute: LearnRoute,
  PreciousMetalRoute: PreciousMetalRoute,
  VaultRoute: VaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
