/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as EarlyAccessRouteImport } from './routes/early-access'
import { Route as FractionalGoldRouteImport } from './routes/fractional-gold'
import { Route as GiftingRouteImport } from './routes/gifting'
import { Route as GiftingOldVerRouteImport } from './routes/gifting-old-ver'
import { Route as HomeOldVerRouteImport } from './routes/home-old-ver'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as PreciousMetalRouteImport } from './routes/precious-metal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrustCenterRouteImport } from './routes/trust-center'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnGiftingGoldGuideRouteImport } from './routes/learn.gifting-gold-guide'
import { Route as LearnHowToBuyGoldSafelyRouteImport } from './routes/learn.how-to-buy-gold-safely'
import { Route as LearnPhysicalGoldVsGoldEtfRouteImport } from './routes/learn.physical-gold-vs-gold-etf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyAccessRoute = EarlyAccessRouteImport.update({
  id: '/early-access',
  path: '/early-access',
  getParentRoute: () => rootRouteImport,
} as any)
const FractionalGoldRoute = FractionalGoldRouteImport.update({
  id: '/fractional-gold',
  path: '/fractional-gold',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftingRoute = GiftingRouteImport.update({
  id: '/gifting',
  path: '/gifting',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftingOldVerRoute = GiftingOldVerRouteImport.update({
  id: '/gifting-old-ver',
  path: '/gifting-old-ver',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeOldVerRoute = HomeOldVerRouteImport.update({
  id: '/home-old-ver',
  path: '/home-old-ver',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const PreciousMetalRoute = PreciousMetalRouteImport.update({
  id: '/precious-metal',
  path: '/precious-metal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustCenterRoute = TrustCenterRouteImport.update({
  id: '/trust-center',
  path: '/trust-center',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const LearnGiftingGoldGuideRoute = LearnGiftingGoldGuideRouteImport.update({
  id: '/gifting-gold-guide',
  path: '/gifting-gold-guide',
  getParentRoute: () => LearnRoute,
} as any)
const LearnHowToBuyGoldSafelyRoute = LearnHowToBuyGoldSafelyRouteImport.update({
  id: '/how-to-buy-gold-safely',
  path: '/how-to-buy-gold-safely',
  getParentRoute: () => LearnRoute,
} as any)
const LearnPhysicalGoldVsGoldEtfRoute =
  LearnPhysicalGoldVsGoldEtfRouteImport.update({
    id: '/physical-gold-vs-gold-etf',
    path: '/physical-gold-vs-gold-etf',
    getParentRoute: () => LearnRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/early-access': typeof EarlyAccessRoute
  '/fractional-gold': typeof FractionalGoldRoute
  '/gifting': typeof GiftingRoute
  '/gifting-old-ver': typeof GiftingOldVerRoute
  '/home-old-ver': typeof HomeOldVerRoute
  '/learn': typeof LearnRouteWithChildren
  '/precious-metal': typeof PreciousMetalRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trust-center': typeof TrustCenterRoute
  '/vault': typeof VaultRoute
  '/learn/gifting-gold-guide': typeof LearnGiftingGoldGuideRoute
  '/learn/how-to-buy-gold-safely': typeof LearnHowToBuyGoldSafelyRoute
  '/learn/physical-gold-vs-gold-etf': typeof LearnPhysicalGoldVsGoldEtfRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/early-access': typeof EarlyAccessRoute
  '/fractional-gold': typeof FractionalGoldRoute
  '/gifting': typeof GiftingRoute
  '/gifting-old-ver': typeof GiftingOldVerRoute
  '/home-old-ver': typeof HomeOldVerRoute
  '/precious-metal': typeof PreciousMetalRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trust-center': typeof TrustCenterRoute
  '/vault': typeof VaultRoute
  '/learn/gifting-gold-guide': typeof LearnGiftingGoldGuideRoute
  '/learn/how-to-buy-gold-safely': typeof LearnHowToBuyGoldSafelyRoute
  '/learn/physical-gold-vs-gold-etf': typeof LearnPhysicalGoldVsGoldEtfRoute
  '/learn': typeof LearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/early-access': typeof EarlyAccessRoute
  '/fractional-gold': typeof FractionalGoldRoute
  '/gifting': typeof GiftingRoute
  '/gifting-old-ver': typeof GiftingOldVerRoute
  '/home-old-ver': typeof HomeOldVerRoute
  '/learn': typeof LearnRouteWithChildren
  '/precious-metal': typeof PreciousMetalRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trust-center': typeof TrustCenterRoute
  '/vault': typeof VaultRoute
  '/learn/gifting-gold-guide': typeof LearnGiftingGoldGuideRoute
  '/learn/how-to-buy-gold-safely': typeof LearnHowToBuyGoldSafelyRoute
  '/learn/physical-gold-vs-gold-etf': typeof LearnPhysicalGoldVsGoldEtfRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/early-access'
    | '/fractional-gold'
    | '/gifting'
    | '/gifting-old-ver'
    | '/home-old-ver'
    | '/learn'
    | '/precious-metal'
    | '/privacy'
    | '/terms'
    | '/trust-center'
    | '/vault'
    | '/learn/gifting-gold-guide'
    | '/learn/how-to-buy-gold-safely'
    | '/learn/physical-gold-vs-gold-etf'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/early-access'
    | '/fractional-gold'
    | '/gifting'
    | '/gifting-old-ver'
    | '/home-old-ver'
    | '/precious-metal'
    | '/privacy'
    | '/terms'
    | '/trust-center'
    | '/vault'
    | '/learn/gifting-gold-guide'
    | '/learn/how-to-buy-gold-safely'
    | '/learn/physical-gold-vs-gold-etf'
    | '/learn'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/early-access'
    | '/fractional-gold'
    | '/gifting'
    | '/gifting-old-ver'
    | '/home-old-ver'
    | '/learn'
    | '/precious-metal'
    | '/privacy'
    | '/terms'
    | '/trust-center'
    | '/vault'
    | '/learn/gifting-gold-guide'
    | '/learn/how-to-buy-gold-safely'
    | '/learn/physical-gold-vs-gold-etf'
    | '/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  EarlyAccessRoute: typeof EarlyAccessRoute
  FractionalGoldRoute: typeof FractionalGoldRoute
  GiftingRoute: typeof GiftingRoute
  GiftingOldVerRoute: typeof GiftingOldVerRoute
  HomeOldVerRoute: typeof HomeOldVerRoute
  LearnRoute: typeof LearnRouteWithChildren
  PreciousMetalRoute: typeof PreciousMetalRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TrustCenterRoute: typeof TrustCenterRoute
  VaultRoute: typeof VaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-access': {
      id: '/early-access'
      path: '/early-access'
      fullPath: '/early-access'
      preLoaderRoute: typeof EarlyAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fractional-gold': {
      id: '/fractional-gold'
      path: '/fractional-gold'
      fullPath: '/fractional-gold'
      preLoaderRoute: typeof FractionalGoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifting': {
      id: '/gifting'
      path: '/gifting'
      fullPath: '/gifting'
      preLoaderRoute: typeof GiftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifting-old-ver': {
      id: '/gifting-old-ver'
      path: '/gifting-old-ver'
      fullPath: '/gifting-old-ver'
      preLoaderRoute: typeof GiftingOldVerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-old-ver': {
      id: '/home-old-ver'
      path: '/home-old-ver'
      fullPath: '/home-old-ver'
      preLoaderRoute: typeof HomeOldVerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precious-metal': {
      id: '/precious-metal'
      path: '/precious-metal'
      fullPath: '/precious-metal'
      preLoaderRoute: typeof PreciousMetalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-center': {
      id: '/trust-center'
      path: '/trust-center'
      fullPath: '/trust-center'
      preLoaderRoute: typeof TrustCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/gifting-gold-guide': {
      id: '/learn/gifting-gold-guide'
      path: '/gifting-gold-guide'
      fullPath: '/learn/gifting-gold-guide'
      preLoaderRoute: typeof LearnGiftingGoldGuideRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/how-to-buy-gold-safely': {
      id: '/learn/how-to-buy-gold-safely'
      path: '/how-to-buy-gold-safely'
      fullPath: '/learn/how-to-buy-gold-safely'
      preLoaderRoute: typeof LearnHowToBuyGoldSafelyRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/physical-gold-vs-gold-etf': {
      id: '/learn/physical-gold-vs-gold-etf'
      path: '/physical-gold-vs-gold-etf'
      fullPath: '/learn/physical-gold-vs-gold-etf'
      preLoaderRoute: typeof LearnPhysicalGoldVsGoldEtfRouteImport
      parentRoute: typeof LearnRoute
    }
  }
}

interface LearnRouteChildren {
  LearnGiftingGoldGuideRoute: typeof LearnGiftingGoldGuideRoute
  LearnHowToBuyGoldSafelyRoute: typeof LearnHowToBuyGoldSafelyRoute
  LearnPhysicalGoldVsGoldEtfRoute: typeof LearnPhysicalGoldVsGoldEtfRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnGiftingGoldGuideRoute: LearnGiftingGoldGuideRoute,
  LearnHowToBuyGoldSafelyRoute: LearnHowToBuyGoldSafelyRoute,
  LearnPhysicalGoldVsGoldEtfRoute: LearnPhysicalGoldVsGoldEtfRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  EarlyAccessRoute: EarlyAccessRoute,
  FractionalGoldRoute: FractionalGoldRoute,
  GiftingRoute: GiftingRoute,
  GiftingOldVerRoute: GiftingOldVerRoute,
  HomeOldVerRoute: HomeOldVerRoute,
  LearnRoute: LearnRouteWithChildren,
  PreciousMetalRoute: PreciousMetalRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TrustCenterRoute: TrustCenterRoute,
  VaultRoute: VaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
