/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AurumRouteImport } from './routes/aurum'
import { Route as EarlyAccessRouteImport } from './routes/early-access'
import { Route as FractionalGoldRouteImport } from './routes/fractional-gold'
import { Route as GiftingRouteImport } from './routes/gifting'
import { Route as GiftingOldVerRouteImport } from './routes/gifting-old-ver'
import { Route as HomeOldVerRouteImport } from './routes/home-old-ver'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as PreciousMetalRouteImport } from './routes/precious-metal'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrustCenterRouteImport } from './routes/trust-center'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminPeopleRouteImport } from './routes/admin.people'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnGiftingGoldGuideRouteImport } from './routes/learn.gifting-gold-guide'
import { Route as LearnHowToBuyGoldSafelyRouteImport } from './routes/learn.how-to-buy-gold-safely'
import { Route as LearnPhysicalGoldVsGoldEtfRouteImport } from './routes/learn.physical-gold-vs-gold-etf'
import { Route as AdminPostsPostIdRouteImport } from './routes/admin.posts.$postId'
import { Route as ApiPublicAurumBackfillDailyHistoryRouteImport } from './routes/api/public/aurum-backfill-daily-history'
import { Route as ApiPublicAurumGoldPriceFetcherRouteImport } from './routes/api/public/aurum-gold-price-fetcher'
import { Route as ApiPublicGetGoldPriceRouteImport } from './routes/api/public/get-gold-price'
import { Route as ApiPublicGetHistoryRouteImport } from './routes/api/public/get-history'
import { Route as AurumBriefsSlugRouteImport } from './routes/aurum_.briefs.$slug'
import { Route as AurumNotesSlugRouteImport } from './routes/aurum_.notes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AurumRoute = AurumRouteImport.update({
  id: '/aurum',
  path: '/aurum',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyAccessRoute = EarlyAccessRouteImport.update({
  id: '/early-access',
  path: '/early-access',
  getParentRoute: () => rootRouteImport,
} as any)
const FractionalGoldRoute = FractionalGoldRouteImport.update({
  id: '/fractional-gold',
  path: '/fractional-gold',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftingRoute = GiftingRouteImport.update({
  id: '/gifting',
  path: '/gifting',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftingOldVerRoute = GiftingOldVerRouteImport.update({
  id: '/gifting-old-ver',
  path: '/gifting-old-ver',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeOldVerRoute = HomeOldVerRouteImport.update({
  id: '/home-old-ver',
  path: '/home-old-ver',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const PreciousMetalRoute = PreciousMetalRouteImport.update({
  id: '/precious-metal',
  path: '/precious-metal',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustCenterRoute = TrustCenterRouteImport.update({
  id: '/trust-center',
  path: '/trust-center',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPeopleRoute = AdminPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const LearnGiftingGoldGuideRoute = LearnGiftingGoldGuideRouteImport.update({
  id: '/gifting-gold-guide',
  path: '/gifting-gold-guide',
  getParentRoute: () => LearnRoute,
} as any)
const LearnHowToBuyGoldSafelyRoute = LearnHowToBuyGoldSafelyRouteImport.update({
  id: '/how-to-buy-gold-safely',
  path: '/how-to-buy-gold-safely',
  getParentRoute: () => LearnRoute,
} as any)
const LearnPhysicalGoldVsGoldEtfRoute =
  LearnPhysicalGoldVsGoldEtfRouteImport.update({
    id: '/physical-gold-vs-gold-etf',
    path: '/physical-gold-vs-gold-etf',
    getParentRoute: () => LearnRoute,
  } as any)
const AdminPostsPostIdRoute = AdminPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AdminPostsRoute,
} as any)
const ApiPublicAurumBackfillDailyHistoryRoute =
  ApiPublicAurumBackfillDailyHistoryRouteImport.update({
    id: '/api/public/aurum-backfill-daily-history',
    path: '/api/public/aurum-backfill-daily-history',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAurumGoldPriceFetcherRoute =
  ApiPublicAurumGoldPriceFetcherRouteImport.update({
    id: '/api/public/aurum-gold-price-fetcher',
    path: '/api/public/aurum-gold-price-fetcher',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGetGoldPriceRoute = ApiPublicGetGoldPriceRouteImport.update({
  id: '/api/public/get-gold-price',
  path: '/api/public/get-gold-price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGetHistoryRoute = ApiPublicGetHistoryRouteImport.update({
  id: '/api/public/get-history',
  path: '/api/public/get-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AurumBriefsSlugRoute = AurumBriefsSlugRouteImport.update({
  id: '/aurum_/briefs/$slug',
  path: '/aurum/briefs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AurumNotesSlugRoute = AurumNotesSlugRouteImport.update({
  id: '/aurum_/notes/$slug',
  path: '/aurum/notes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRouteWithChildren
  '/aurum': typeof AurumRoute
  '/early-access': typeof EarlyAccessRoute
  '/fractional-gold': typeof FractionalGoldRoute
  '/gifting': typeof GiftingRoute
  '/gifting-old-ver': typeof GiftingOldVerRoute
  '/home-old-ver': typeof HomeOldVerRoute
  '/learn': typeof LearnRouteWithChildren
  '/precious-metal': typeof PreciousMetalRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trust-center': typeof TrustCenterRoute
  '/vault': typeof VaultRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/learn/gifting-gold-guide': typeof LearnGiftingGoldGuideRoute
  '/learn/how-to-buy-gold-safely': typeof LearnHowToBuyGoldSafelyRoute
  '/learn/physical-gold-vs-gold-etf': typeof LearnPhysicalGoldVsGoldEtfRoute
  '/admin/': typeof AdminIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/admin/posts/$postId': typeof AdminPostsPostIdRoute
  '/api/public/aurum-backfill-daily-history': typeof ApiPublicAurumBackfillDailyHistoryRoute
  '/api/public/aurum-gold-price-fetcher': typeof ApiPublicAurumGoldPriceFetcherRoute
  '/api/public/get-gold-price': typeof ApiPublicGetGoldPriceRoute
  '/api/public/get-history': typeof ApiPublicGetHistoryRoute
  '/aurum/briefs/$slug': typeof AurumBriefsSlugRoute
  '/aurum/notes/$slug': typeof AurumNotesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/aurum': typeof AurumRoute
  '/early-access': typeof EarlyAccessRoute
  '/fractional-gold': typeof FractionalGoldRoute
  '/gifting': typeof GiftingRoute
  '/gifting-old-ver': typeof GiftingOldVerRoute
  '/home-old-ver': typeof HomeOldVerRoute
  '/precious-metal': typeof PreciousMetalRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trust-center': typeof TrustCenterRoute
  '/vault': typeof VaultRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/learn/gifting-gold-guide': typeof LearnGiftingGoldGuideRoute
  '/learn/how-to-buy-gold-safely': typeof LearnHowToBuyGoldSafelyRoute
  '/learn/physical-gold-vs-gold-etf': typeof LearnPhysicalGoldVsGoldEtfRoute
  '/admin': typeof AdminIndexRoute
  '/learn': typeof LearnIndexRoute
  '/admin/posts/$postId': typeof AdminPostsPostIdRoute
  '/api/public/aurum-backfill-daily-history': typeof ApiPublicAurumBackfillDailyHistoryRoute
  '/api/public/aurum-gold-price-fetcher': typeof ApiPublicAurumGoldPriceFetcherRoute
  '/api/public/get-gold-price': typeof ApiPublicGetGoldPriceRoute
  '/api/public/get-history': typeof ApiPublicGetHistoryRoute
  '/aurum/briefs/$slug': typeof AurumBriefsSlugRoute
  '/aurum/notes/$slug': typeof AurumNotesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRouteWithChildren
  '/aurum': typeof AurumRoute
  '/early-access': typeof EarlyAccessRoute
  '/fractional-gold': typeof FractionalGoldRoute
  '/gifting': typeof GiftingRoute
  '/gifting-old-ver': typeof GiftingOldVerRoute
  '/home-old-ver': typeof HomeOldVerRoute
  '/learn': typeof LearnRouteWithChildren
  '/precious-metal': typeof PreciousMetalRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trust-center': typeof TrustCenterRoute
  '/vault': typeof VaultRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/learn/gifting-gold-guide': typeof LearnGiftingGoldGuideRoute
  '/learn/how-to-buy-gold-safely': typeof LearnHowToBuyGoldSafelyRoute
  '/learn/physical-gold-vs-gold-etf': typeof LearnPhysicalGoldVsGoldEtfRoute
  '/admin/': typeof AdminIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/admin/posts/$postId': typeof AdminPostsPostIdRoute
  '/api/public/aurum-backfill-daily-history': typeof ApiPublicAurumBackfillDailyHistoryRoute
  '/api/public/aurum-gold-price-fetcher': typeof ApiPublicAurumGoldPriceFetcherRoute
  '/api/public/get-gold-price': typeof ApiPublicGetGoldPriceRoute
  '/api/public/get-history': typeof ApiPublicGetHistoryRoute
  '/aurum_/briefs/$slug': typeof AurumBriefsSlugRoute
  '/aurum_/notes/$slug': typeof AurumNotesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/admin'
    | '/aurum'
    | '/early-access'
    | '/fractional-gold'
    | '/gifting'
    | '/gifting-old-ver'
    | '/home-old-ver'
    | '/learn'
    | '/precious-metal'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/trust-center'
    | '/vault'
    | '/admin/people'
    | '/admin/posts'
    | '/admin/settings'
    | '/learn/gifting-gold-guide'
    | '/learn/how-to-buy-gold-safely'
    | '/learn/physical-gold-vs-gold-etf'
    | '/admin/'
    | '/learn/'
    | '/admin/posts/$postId'
    | '/api/public/aurum-backfill-daily-history'
    | '/api/public/aurum-gold-price-fetcher'
    | '/api/public/get-gold-price'
    | '/api/public/get-history'
    | '/aurum/briefs/$slug'
    | '/aurum/notes/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/aurum'
    | '/early-access'
    | '/fractional-gold'
    | '/gifting'
    | '/gifting-old-ver'
    | '/home-old-ver'
    | '/precious-metal'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/trust-center'
    | '/vault'
    | '/admin/people'
    | '/admin/posts'
    | '/admin/settings'
    | '/learn/gifting-gold-guide'
    | '/learn/how-to-buy-gold-safely'
    | '/learn/physical-gold-vs-gold-etf'
    | '/admin'
    | '/learn'
    | '/admin/posts/$postId'
    | '/api/public/aurum-backfill-daily-history'
    | '/api/public/aurum-gold-price-fetcher'
    | '/api/public/get-gold-price'
    | '/api/public/get-history'
    | '/aurum/briefs/$slug'
    | '/aurum/notes/$slug'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/admin'
    | '/aurum'
    | '/early-access'
    | '/fractional-gold'
    | '/gifting'
    | '/gifting-old-ver'
    | '/home-old-ver'
    | '/learn'
    | '/precious-metal'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/trust-center'
    | '/vault'
    | '/admin/people'
    | '/admin/posts'
    | '/admin/settings'
    | '/learn/gifting-gold-guide'
    | '/learn/how-to-buy-gold-safely'
    | '/learn/physical-gold-vs-gold-etf'
    | '/admin/'
    | '/learn/'
    | '/admin/posts/$postId'
    | '/api/public/aurum-backfill-daily-history'
    | '/api/public/aurum-gold-price-fetcher'
    | '/api/public/get-gold-price'
    | '/api/public/get-history'
    | '/aurum_/briefs/$slug'
    | '/aurum_/notes/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AdminRoute: typeof AdminRouteWithChildren
  AurumRoute: typeof AurumRoute
  EarlyAccessRoute: typeof EarlyAccessRoute
  FractionalGoldRoute: typeof FractionalGoldRoute
  GiftingRoute: typeof GiftingRoute
  GiftingOldVerRoute: typeof GiftingOldVerRoute
  HomeOldVerRoute: typeof HomeOldVerRoute
  LearnRoute: typeof LearnRouteWithChildren
  PreciousMetalRoute: typeof PreciousMetalRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TrustCenterRoute: typeof TrustCenterRoute
  VaultRoute: typeof VaultRoute
  ApiPublicAurumBackfillDailyHistoryRoute: typeof ApiPublicAurumBackfillDailyHistoryRoute
  ApiPublicAurumGoldPriceFetcherRoute: typeof ApiPublicAurumGoldPriceFetcherRoute
  ApiPublicGetGoldPriceRoute: typeof ApiPublicGetGoldPriceRoute
  ApiPublicGetHistoryRoute: typeof ApiPublicGetHistoryRoute
  AurumBriefsSlugRoute: typeof AurumBriefsSlugRoute
  AurumNotesSlugRoute: typeof AurumNotesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aurum': {
      id: '/aurum'
      path: '/aurum'
      fullPath: '/aurum'
      preLoaderRoute: typeof AurumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-access': {
      id: '/early-access'
      path: '/early-access'
      fullPath: '/early-access'
      preLoaderRoute: typeof EarlyAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fractional-gold': {
      id: '/fractional-gold'
      path: '/fractional-gold'
      fullPath: '/fractional-gold'
      preLoaderRoute: typeof FractionalGoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifting': {
      id: '/gifting'
      path: '/gifting'
      fullPath: '/gifting'
      preLoaderRoute: typeof GiftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifting-old-ver': {
      id: '/gifting-old-ver'
      path: '/gifting-old-ver'
      fullPath: '/gifting-old-ver'
      preLoaderRoute: typeof GiftingOldVerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-old-ver': {
      id: '/home-old-ver'
      path: '/home-old-ver'
      fullPath: '/home-old-ver'
      preLoaderRoute: typeof HomeOldVerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precious-metal': {
      id: '/precious-metal'
      path: '/precious-metal'
      fullPath: '/precious-metal'
      preLoaderRoute: typeof PreciousMetalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-center': {
      id: '/trust-center'
      path: '/trust-center'
      fullPath: '/trust-center'
      preLoaderRoute: typeof TrustCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/people': {
      id: '/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AdminPeopleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/gifting-gold-guide': {
      id: '/learn/gifting-gold-guide'
      path: '/gifting-gold-guide'
      fullPath: '/learn/gifting-gold-guide'
      preLoaderRoute: typeof LearnGiftingGoldGuideRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/how-to-buy-gold-safely': {
      id: '/learn/how-to-buy-gold-safely'
      path: '/how-to-buy-gold-safely'
      fullPath: '/learn/how-to-buy-gold-safely'
      preLoaderRoute: typeof LearnHowToBuyGoldSafelyRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/physical-gold-vs-gold-etf': {
      id: '/learn/physical-gold-vs-gold-etf'
      path: '/physical-gold-vs-gold-etf'
      fullPath: '/learn/physical-gold-vs-gold-etf'
      preLoaderRoute: typeof LearnPhysicalGoldVsGoldEtfRouteImport
      parentRoute: typeof LearnRoute
    }
    '/admin/posts/$postId': {
      id: '/admin/posts/$postId'
      path: '/$postId'
      fullPath: '/admin/posts/$postId'
      preLoaderRoute: typeof AdminPostsPostIdRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/api/public/aurum-backfill-daily-history': {
      id: '/api/public/aurum-backfill-daily-history'
      path: '/api/public/aurum-backfill-daily-history'
      fullPath: '/api/public/aurum-backfill-daily-history'
      preLoaderRoute: typeof ApiPublicAurumBackfillDailyHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/aurum-gold-price-fetcher': {
      id: '/api/public/aurum-gold-price-fetcher'
      path: '/api/public/aurum-gold-price-fetcher'
      fullPath: '/api/public/aurum-gold-price-fetcher'
      preLoaderRoute: typeof ApiPublicAurumGoldPriceFetcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/get-gold-price': {
      id: '/api/public/get-gold-price'
      path: '/api/public/get-gold-price'
      fullPath: '/api/public/get-gold-price'
      preLoaderRoute: typeof ApiPublicGetGoldPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/get-history': {
      id: '/api/public/get-history'
      path: '/api/public/get-history'
      fullPath: '/api/public/get-history'
      preLoaderRoute: typeof ApiPublicGetHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aurum_/briefs/$slug': {
      id: '/aurum_/briefs/$slug'
      path: '/aurum/briefs/$slug'
      fullPath: '/aurum/briefs/$slug'
      preLoaderRoute: typeof AurumBriefsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aurum_/notes/$slug': {
      id: '/aurum_/notes/$slug'
      path: '/aurum/notes/$slug'
      fullPath: '/aurum/notes/$slug'
      preLoaderRoute: typeof AurumNotesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminPostsRouteChildren {
  AdminPostsPostIdRoute: typeof AdminPostsPostIdRoute
}

const AdminPostsRouteChildren: AdminPostsRouteChildren = {
  AdminPostsPostIdRoute: AdminPostsPostIdRoute,
}

const AdminPostsRouteWithChildren = AdminPostsRoute._addFileChildren(
  AdminPostsRouteChildren,
)

interface AdminRouteChildren {
  AdminPeopleRoute: typeof AdminPeopleRoute
  AdminPostsRoute: typeof AdminPostsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPeopleRoute: AdminPeopleRoute,
  AdminPostsRoute: AdminPostsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LearnRouteChildren {
  LearnGiftingGoldGuideRoute: typeof LearnGiftingGoldGuideRoute
  LearnHowToBuyGoldSafelyRoute: typeof LearnHowToBuyGoldSafelyRoute
  LearnPhysicalGoldVsGoldEtfRoute: typeof LearnPhysicalGoldVsGoldEtfRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnGiftingGoldGuideRoute: LearnGiftingGoldGuideRoute,
  LearnHowToBuyGoldSafelyRoute: LearnHowToBuyGoldSafelyRoute,
  LearnPhysicalGoldVsGoldEtfRoute: LearnPhysicalGoldVsGoldEtfRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AdminRoute: AdminRouteWithChildren,
  AurumRoute: AurumRoute,
  EarlyAccessRoute: EarlyAccessRoute,
  FractionalGoldRoute: FractionalGoldRoute,
  GiftingRoute: GiftingRoute,
  GiftingOldVerRoute: GiftingOldVerRoute,
  HomeOldVerRoute: HomeOldVerRoute,
  LearnRoute: LearnRouteWithChildren,
  PreciousMetalRoute: PreciousMetalRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TrustCenterRoute: TrustCenterRoute,
  VaultRoute: VaultRoute,
  ApiPublicAurumBackfillDailyHistoryRoute:
    ApiPublicAurumBackfillDailyHistoryRoute,
  ApiPublicAurumGoldPriceFetcherRoute: ApiPublicAurumGoldPriceFetcherRoute,
  ApiPublicGetGoldPriceRoute: ApiPublicGetGoldPriceRoute,
  ApiPublicGetHistoryRoute: ApiPublicGetHistoryRoute,
  AurumBriefsSlugRoute: AurumBriefsSlugRoute,
  AurumNotesSlugRoute: AurumNotesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
